name: runners_social
description: A social running app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^7.9.0
  dio: ^5.7.0
  flutter_riverpod: ^2.4.9
  riverpod: ^2.4.9
  flutter_secure_storage: ^9.2.2
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  socket_io_client: ^2.0.3+1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
