name: runners_social
description: A real-time social app for runners
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.1
  flutter_sound: ^9.2.13
  just_audio: ^0.9.35
  permission_handler: ^11.0.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
