name: runners_social
description: A social running app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  socket_io_client: ^2.0.3+1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  uuid: ^4.2.2
  intl: ^0.19.0
  lottie: ^2.7.0
  get_it: ^7.6.7
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
